Repository googleapis/python-access-approval, pull requests merged in 2020-05, with the labels that each got.

#2 docs: add support badge and PyPI badge to README
  README.rst
Labels: cla: yes

#10 docs: add multiprocessing note (via synth)
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/accessapproval_v1/proto/accessapproval_pb2.py
  synth.metadata
Labels: cla: yes

#11 fix: update readme
  README.rst
Labels: automerge, cla: yes

#17 chore: remove extra bash line
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  google/cloud/accessapproval_v1/proto/accessapproval_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#16 chore: change docstring line spacing
  google/cloud/accessapproval_v1/proto/accessapproval_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#20 bazel: update protobuf, rules_go, gazelle, and gapic-generator-go versions
  google/cloud/accessapproval_v1/proto/accessapproval_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#19 chore: update docstring formatting
  synth.metadata
Labels: automerge, cla: yes, context: none
