Repository googleapis/python-access-approval, pull requests merged in 2021-03, with the labels that each got.

#48 chore: update templates
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#55 Upgrade client library from beta to GA
  .repo-metadata.json
  README.rst
  setup.py
Labels: api: accessapproval, cla: yes

#46 chore: update synth metadata sources
  accessapproval-v1-py.tar.gz
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: none
