Repository googleapis/python-access-approval, pull requests merged in 2021-04, with the labels that each got.

#62 chore: add tarfile
  accessapproval-v1-py.tar.gz
  synth.metadata
Labels: api: accessapproval, cla: yes, context: none

#64 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#65 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: accessapproval, cla: yes, context: full, samples

#67 chore: prevent normalization of semver versioning
  setup.py
Labels: api: accessapproval, cla: yes

#66 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#69 chore(revert): revert preventing normalization
  setup.py
Labels: api: accessapproval, cla: yes
